dist: xenial
language: cpp

os: linux

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-8
      - clang-8
script:
  - clang-8 -v
  - clang++8 -v
