name: x86-Ubuntu-llvm-from-sources-static

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Download Ninja
        shell: cmake -P {0}
        run: |
          # The following steps are implemented using CMake commands
          set(ninja_version "1.9.0")
          set(ninja_suffix "linux.zip")
          set(ninja_url "https://github.com/ninja-build/ninja/releases/download/v${ninja_version}/ninja-${ninja_suffix}")
          file(DOWNLOAD "${ninja_url}" ./ninja.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ninja.zip)

          if (NOT "${{ runner.os }}" STREQUAL "Windows")
            execute_process(
            COMMAND chmod +x ninja
            )
          endif()
      - name: Clone llvm-project
        run: |
          git clone --depth 10 --single-branch --branch release/12.x https://github.com/llvm/llvm-project
          cd llvm-project
      - name: Register MBAAdd statically
        run: |
          bash utils/static_registration.sh --llvm_project_dir "$GITHUB_WORKSPACE/llvm-project"
      - name: Build LLVM
        run: |
          # Adding the location of Ninja to $PATH
          export PATH=$GITHUB_WORKSPACE:$PATH
          cd llvm-project
          mkdir build && cd build
          ln -s /usr/bin/x86_64-linux-gnu-ld.gold ld
          cmake -G Ninja -D CMAKE_MAKE_PROGRAM=$GITHUB_WORKSPACE/ninja \
            -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD="host" -DLLVM_OPTIMIZED_TABLEGEN=ON \
            -DLLVM_BUILD_EXAMPLES=On -DLLVM_MBASUB_LINK_INTO_TOOLS=On \
            ../llvm
          # Note that only the required tools are built
          ninja
      - name: Install lit
        run: |
          sudo pip3 install lit
      - name: Run MBASub - sanity check
        run: |
          $GITHUB_WORKSPACE/llvm-project/build/bin/opt -passes=mba-sub -S $GITHUB_WORKSPACE/test/MBA_sub.ll
      - name: Run MBASub tests
        run: |
          $GITHUB_WORKSPACE/llvm-project/build/bin/llvm-lit $GITHUB_WORKSPACE/llvm-project/llvm/test/Examples/MBASub/
